esphome:
  name: pir00
  platform: ESP8266
  board: esp01_1m
  arduino_version: 2.4.2
  esphome_core_version: dev
  board_flash_mode: dout
  build_path: .build
  includes:
    - sb1_uart.h

substitutions: !include .substitutions.yaml

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true

mqtt:
  broker: ${mqtt_broker}
  will_message:

uart:
  - tx_pin: 1
    rx_pin: 3
    baud_rate: 9600
    id: uart0

ota:

logger:
  level: INFO
  id: logger
  hardware_uart: UART1

sensor:
  - platform: wifi_signal
    id: wifi_signal
    name: "PIR00 WiFi Signal"
    expire_after:
    filters: []
  - platform: adc
    id: voltage
    name: "PIR00 Battery"
    expire_after:
    pin: VCC
    filters: []

binary_sensor:
  - platform: template
    id: motion
    name: "PIR00 Motion"
    filters: []
    device_class: motion
    lambda: "return {};"

custom_component:
  - id: sb1_uart
    lambda: |-
      auto component = new SB1UARTComponent(id(uart0), id(motion));
      return {component};
